---
title: 'Portfolio: Chris Martin'
output:
  html_document:
    df_print: paged

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

# Data cleaning

| Brief project description | Techniques used | Key learning resources |
|---------------------------|-----------------|------------------------|
|                           |                 |                        |
|                           |                 |                        |
|                           |                 |                        |

# Exploratory data analysis

| Brief project description | Techniques used | Key learning resources |
|---------------------------|-----------------|------------------------|
|                           |                 |                        |
|                           |                 |                        |
|                           |                 |                        |

# Supervised Learning

| Brief project description                                                                                                                                                                               | Techniques used                                          | Key learning resources                                                   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------|--------------------------------------------------------------------------|
| [Developing a linear regression model to predict the amount of plastic waste a country produces each year](https://tbk03.github.io/portfolio_chris_martin/plastics_regression_1.html).                  | Linear regression, posterior predictive graphical checks | [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/) |
| Visualising the interaction between a continuous predictor and a categorical predictor in a linear regression model. Applied to the problem of problem of estimate per capita plastic waste production. | Linear regression                                        | [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/) |
|                                                                                                                                                                                                         |                                                          |                                                                          |

# Unsupervised learning

| Brief project description                                                   | Tools and Techniques used           | Key learning resources                                                                                                                                                            |
|-----------------------------------------------------------------------------|-------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Exploring common forms of green space deprivation in English neighborhoods. | PCA, k-means clustering, tidymodels | [An Introduction to Statistical Learning](https://static1.squarespace.com/static/5ff2adbe3fe4fe33db902812/t/6062a083acbfe82c7195b27d/1617076404560/ISLR%2BSeventh%2BPrinting.pdf) |

# Statistical inference

| Brief project description                                               | Techniques used | Key learning resources |
|-------------------------------------------------------------------------|-----------------|------------------------|
| Estimating the green space deprivation experiences of the UK population | simulation,     |                        |

# Data visualisation

| Brief project description                                                                                                                                                                                                              | Tools and techniques used              | Key learning resources                                                                                                                           |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| Visualising green space deprivation across the English regions ([code](https://tbk03.github.io/portfolio_chris_martin/green_space_viz_1.html), [visualisation](https://pbs.twimg.com/media/EwnlJO9WUAII-BO?format=png&name=4096x4096)) | ggplot2, waffle charts, data wrangling | a \#TidyTuesday [visualization produced by cxinya](https://github.com/cxinya/tidy-tuesday/blob/main/2021_week-11_bechdel/2021_week-11_bechdel.R) |
